FROM pgrouting/pgrouting:17-3.5-3.8

COPY Webgis_QuyNhon.backup /docker-entrypoint-initdb.d/20-webgis.backup
COPY docker/init-db.sh /docker-entrypoint-initdb.d/30-restore-webgis.sh

RUN chmod +x /docker-entrypoint-initdb.d/30-restore-webgis.sh
